spring:
  application:
    name: User-Microservice
#    Connect to config server
  config:
    import: configserver:http://localhost:8888
#    Profile
  profiles:
    active: dev
    #Database configuration
  data:
    mongodb:
      uri: ${uri}
#      For container based DB
#      authentication-database: admin
      database: user-microservice-database

#Server configuration
server:
  port: ${USER_PORT_NO}