spring:
  application:
    name: User-Microservice
#    Connect to config server
  config:
    import: configserver:http://localhost:8888
#    Profile
  profiles:
    active: dev
    #Database configuration
  data:
    mongodb:
      uri: ${uri}
#      For container based DB
#      authentication-database: admin
      database: user-microservice-database

#Server configuration
server:
  port: ${USER_PORT_NO}

#Spring Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#Logging
logging:
  file:
    name: log/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7