spring:
  application:
    name: user-service
    #Database configuration
  data:
    mongodb:
      uri: mongodb+srv://mongodb:<password>@user-microservice-datab.91ul3by.mongodb.net/?retryWrites=true&w=majority&appName=user-microservice-database
#      For container based DB
#      authentication-database: admin
      database: user-microservice-database

#Server configuration
server:
  port: 8082