services:

#  PostgreSQL Container
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kaif@12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped

#    MongoDB Container
#  mongodb:
#    container_name: mongodb_container # A unique name for your MongoDB container
#    image: mongo:latest             # Use 'mongo' image (latest stable version)
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongodb  # Root username for MongoDB
#      MONGO_INITDB_ROOT_PASSWORD: Kaif12345 # Root password for MongoDB
##      MONGO_INITDB_DATABASE: your_database # Optional: default database to create
#    volumes:
#      - mongodb_data:/data/db       # Mount a named volume for persistent data
#    ports:
#      - "27017:27017"               # Map container port 27017 to host port 27017 (default MongoDB port)
#    networks:
#      - my-network                 # Connect to a custom network (recommended)
#    restart: unless-stopped

  #  PgAdmin Container
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
#  mongodb_data: