spring:
  application:
    name: Product-Microservice
#    Connecting to ConfigServer
  config:
    import: configserver:http://localhost:8888
#  Profile
  profiles:
    active: dev
  #  for adding RabbitMQ in configserver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #Database configuration
  datasource:
    url: ${url}
    username: ${DB_USERNAME}
    password: ${password}

#Server configuration
server:
  port: ${PRODUCT_PORT_NO}

#Spring Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true