spring:
  application:
    name: Order-Microservice
    #Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/orderDB
    username: root
    password: Kaif12345


  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      format-sql: true

#Server configuration
server:
  port: 8083