spring:
  application:
    name: Order-Microservice
  #    Connecting to ConfigServer
  config:
    import: configserver:http://localhost:8888
  #Profile
  profiles:
    active: dev
  #  for adding RabbitMQ in configserver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #Database configuration
  datasource:
    url: ${url}
    username: ${DB_USERNAME}
    password: ${password}

#Server configuration
server:
  port: ${ORDER_PORT_NO}

#Spring Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#Logging
logging:
  level:
    root: INFO # Sets the default logging level for all loggers
    Order-Microservice: DEBUG # Sets the logging level for your specific application package to DEBUG
    org.springframework: INFO # Sets the logging level for Spring framework components
    org.hibernate: INFO