spring:
  application:
    name: Order-Microservice
    #Database configuration
  datasource:
    url: jdbc:postgresql://ep-gentle-base-a1039orq-pooler.ap-southeast-1.aws.neon.tech/orderDB?sslmode=require&channel_binding=require
    username: <username>
    password: <password>


  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format-sql: true

#Server configuration
server:
  port: 8083