spring:
  application:
    name: Order-Microservice
  #    Connecting to ConfigServer
  config:
    import: configserver:http://localhost:8888
  #Profile
  profiles:
    active: dev
  #  for adding RabbitMQ in configserver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #Database configuration
  datasource:
    url: ${url}
    username: ${DB_USERNAME}
    password: ${password}

#Server configuration
server:
  port: ${ORDER_PORT_NO}

#Spring Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

#Logging
logging:
  file:
    name: log/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7