spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kaif0705/Config-Server
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: master
#  for adding RabbitMQ in configserver, for this we need to run RabbitMQ in a container
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#expose Spring Boot Actuator busrefresh endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8888

#encrypt:
#  key: "0E329232EA6D0D73"